### ISSUE TITLE
Support for async function?

### ISSUE THREAD

**Issue by IniZio** [blakeembrey/javascript-stringify#23]
Hi many thanks for authoring this library, honestly never thought it is possible to stringify js code before. :)

I noticed that this library does not support async functions, which is supported in nodejs LTS currently.

I might try to work out a PR if such enhancement is suitable, though I do not fully understand the logic yet so it might need some time to figure out.

**Comment by blakeembrey** [comment]
@IniZio I believe this is covered by https://github.com/blakeembrey/javascript-stringify/pull/22, but it's a complex change so I haven't landed it yet. Give me a few weeks and it'll be in a 2.0 release.

**Comment by IniZio** [comment]
Yea I also noticed that, just making a custom package for my own usage for now,looking forward to that release :)

**Comment by IniZio** [comment]
I am closing this since the rewrite has been merged. thanks for the library :)
