### ISSUE TITLE
Add support for dangling commas

### ISSUE THREAD

**Issue by quilicicf** [blakeembrey/javascript-stringify#28]
Hi, 

Thanks for developing this, it is useful.

It would be super nice if you could add dangling commas as an option though. Would make it pass linting in cases where it's required.

I currently proceed like so: 
```js
stringify(object, null, 2)
    .replace(/([^,;{[])\n/g, '$1,\n'); // Adds dangling commas
```
But that's a bit sub-optimal.

**Comment by blakeembrey** [comment]
Passing every listing configuration is out of scope of this package, but feel free to submit a PR if you’d like to see this. You’re better off using a JS formatter on the output of this package to get what you want. Alternatively, you can override the stringifier.

**Comment by quilicicf** [comment]
I tried with the stringifier but got a bit lost with indentation in nested objects. I didn't have much time to dig in so I opted for the dirty solution.

I'll try to add the option though. Having read this package's code, it seems simple enough.

**Comment by quilicicf** [comment]
It seems if I want to add dangling commas, I'll need to pass the option down to `rawObjectToString` in `object.ts`.

This means changing the signature of all the `toString` methods from `(value, space, next, key)` to `(value, space, next, key, options)`. I'm not sure this is a change that would bring much value compared to the added complexity.

I managed to re-format my file using the eslint config in my repo with the code below:

```js
const { writeFileSync } = require('fs');
const { CLIEngine } = require('eslint');
const { resolve, relative } = require('path');

const cwd = resolve(__dirname, '..', '..', '..');
const configFile = resolve(cwd, '.eslintrc.yaml');
const absolutePathToFile = resolve(__dirname, 'myGeneratedFile.js');
const relativePathToFile = relative(cwd, absolutePathToFile);

module.exports = () => {
  const cli = new CLIEngine({ fix: true, cwd, configFile });

  const { results } = cli.executeOnFiles([ relativePathToFile ]);
  const outputToWrite = results[ 0 ].output;
  writeFileSync(absolutePathToFile, outputToWrite, 'utf8');
};
```

I can write a section in the documentation if you think that would help your users.

**Comment by blakeembrey** [comment]
Sure, happy to accept this in the README if we can boil it down to the essentials. I typically use packages like `prettier` myself.

**Comment by quilicicf** [comment]
I'll give it a shot then!

**Comment by quilicicf** [comment]
See PR above :point_up:

**Comment by quilicicf** [comment]
PR merged, thanks.
