### ISSUE TITLE
stringifying an error is funny

### ISSUE THREAD

**Issue by samuelt1** [blakeembrey/javascript-stringify#30]
The following:
```
import { stringify } from 'javascript-stringify'
stringify(new Error('problem'))
```
 stringifies like so:
`"new Error('problem')"`

I was hoping it would stringify something more like:
`'{"message":"problem","stack":"Error: hi\nat <anonymous>:1:5 [<root>]","name":"Error"}'`

I overcame this using custom replacers, which might be the only real solution seeing as how widely used this package is:
```
stringify(error , (obj) => {
  if (obj instanceof Error) {
    return stringify({
      message: obj.message,
      stack: obj.stack,
      name: obj.name,
    })
  } else {
    return stringify(obj)
  }
}, null, { references: true })
```

**Comment by blakeembrey** [comment]
Yes, using a custom replacer would be the best approach here. The goal is to replicate JavaScript as closely as possible, so the current behavior is preferable. Anywhere you'd want to deviate from outputting JavaScript you should override.
