### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by zalmoxisus** [blakeembrey/javascript-stringify#4]
Hey @blakeembrey,

It seems you reverted [my pr](https://github.com/blakeembrey/javascript-stringify/commit/1490bc506cd0da70c33a6bb9a172dbb82dce22c3) in https://github.com/blakeembrey/javascript-stringify/commit/77add2892fd4eedaaeae77405bb5b4cbecf1ef9d.

The problem is that `value` is not `undefined`, but `stringify(value)` is.

**Comment by blakeembrey** [comment]
Thanks. I would have added tests, but I got lazy with everything going on. I'll add a test next time.

**Comment by blakeembrey** [comment]
Tests added with https://github.com/blakeembrey/javascript-stringify/commit/36ac373b782b9b1b4503dc4f3caef0b7a800998f. I'll have to ask for those in the future to avoid dumb mistakes like this 😄
